package com.edua.beeduasystem.domain.model.ai;

/** Nhóm chỉ dẫn hệ thống mà IT Staff có thể cấu hình. */
public enum AiPromptKey {
    LESSON_PLAN_OBJECTIVES,
    LESSON_PLAN_MATERIALS,
    LESSON_PLAN_ACTIVITIES_FRAME,
    LESSON_PLAN_ACTIVITY_DETAIL,
    LESSON_PLAN_EDIT_SECTION,
    SLIDE_OUTLINE_DECK_BLUEPRINT,
    SLIDE_OUTLINE_CONTENT_MAP,
    SLIDE_OUTLINE_STRUCTURE,
    SLIDE_OUTLINE_MERGED,
    SLIDE_OUTLINE_PART_SKELETON,
    SLIDE_OUTLINE_EXPAND_PART,
    SLIDE_OUTLINE_CONSOLIDATE,
    SLIDE_DESIGN_BACKGROUND,
    SLIDE_DESIGN_STRUCTURE,
    SLIDE_DESIGN_CONTENT_FILL,
    SLIDE_DESIGN_CONTENT_SLOTS,
    MOLECULE_STRUCTURE
}
