package com.edua.beeduasystem.domain.model.activitylog;

public enum ActivityLogAction {
    LOGIN,
    LOGOUT,
    GRANT_MODERATOR,
    REPLACE_MODERATOR,
    REACTIVATE_MODERATOR,
    GRANT_IT_STAFF,
    REPLACE_IT_STAFF,
    REVOKE_IT_STAFF,
    REACTIVATE_IT_STAFF,
    GRANT_TEACHER,
    UPDATE_TEACHER,
    REVOKE_TEACHER,
    REACTIVATE_TEACHER,
    APPROVE_LIBRARY_CONTENT,
    REJECT_LIBRARY_CONTENT,
    REMOVE_BLOG_POST,
    APPROVE_WEEKLY_TASK,
    REJECT_WEEKLY_TASK,
    UPDATE_SYSTEM_PROMPT
}
