import type { AtomicWeight, Element } from './types';
import { representativeIsotopeFor } from './representative-isotopes';
import { PERIODIC_TABLE_SNAPSHOT_METADATA } from './periodic-table-sources';
import { PUBCHEM_PROPERTIES } from './snapshot-pubchem-properties';

/**
 * Reviewed static snapshot.  It is committed with the frontend so the UI
 * never fetches scientific data at runtime.  `sync-periodic-table-data.mjs`
 * is the only refresh path and the audit validates this shape before use.
 */
const SNAPSHOT_RECORDS = [
  // ─── Period 1 ───
  { atomicNumber: 1,  symbol: 'H',  name: 'Hydrogen',     nameVi: 'Hiđro',      atomicMass: 1.008,   category: 'nonmetal',        block: 's', period: 1, group: 1,  gridRow: 1, gridCol: 1,  electronConfig: '1s¹',                    protons: 1,   neutrons: 0,  electrons: 1,   meltingPoint: -259.14, boilingPoint: -252.87, density: 0.0000899, electronegativity: 2.20, ionizationEnergy: 1312, electronAffinity: 72.8,  atomicRadius: 53,  specificHeat: 14.304, state: 'gas' },
  { atomicNumber: 2,  symbol: 'He', name: 'Helium',       nameVi: 'Heli',       atomicMass: 4.003,   category: 'noble-gas',       block: 's', period: 1, group: 18, gridRow: 1, gridCol: 18, electronConfig: '1s²',                    protons: 2,   neutrons: 2,  electrons: 2,   meltingPoint: -272.20, boilingPoint: -268.90, density: 0.000164,  electronegativity: null, ionizationEnergy: 2372, electronAffinity: 0,     atomicRadius: 31,  specificHeat: 5.193,  state: 'gas' },
  // ─── Period 2 ───
  { atomicNumber: 3,  symbol: 'Li', name: 'Lithium',      nameVi: 'Liti',       atomicMass: 6.941,   category: 'alkali-metal',    block: 's', period: 2, group: 1,  gridRow: 2, gridCol: 1,  electronConfig: '[He] 2s¹',               protons: 3,   neutrons: 4,  electrons: 3,   meltingPoint: 180.50,  boilingPoint: 1342,    density: 0.534,     electronegativity: 0.98, ionizationEnergy: 520,  electronAffinity: 59.6,  atomicRadius: 167, specificHeat: 3.582,  state: 'solid' },
  { atomicNumber: 4,  symbol: 'Be', name: 'Beryllium',    nameVi: 'Beri',       atomicMass: 9.012,   category: 'alkaline-earth',  block: 's', period: 2, group: 2,  gridRow: 2, gridCol: 2,  electronConfig: '[He] 2s²',               protons: 4,   neutrons: 5,  electrons: 4,   meltingPoint: 1287,    boilingPoint: 2470,    density: 1.85,      electronegativity: 1.57, ionizationEnergy: 900,  electronAffinity: -48,   atomicRadius: 112, specificHeat: 1.825,  state: 'solid' },
  { atomicNumber: 5,  symbol: 'B',  name: 'Boron',        nameVi: 'Bo',         atomicMass: 10.811,  category: 'metalloid',       block: 'p', period: 2, group: 13, gridRow: 2, gridCol: 13, electronConfig: '[He] 2s² 2p¹',           protons: 5,   neutrons: 6,  electrons: 5,   meltingPoint: 2075,    boilingPoint: 4000,    density: 2.34,      electronegativity: 2.04, ionizationEnergy: 801,  electronAffinity: 26.7,  atomicRadius: 87,  specificHeat: 1.026,  state: 'solid' },
  { atomicNumber: 6,  symbol: 'C',  name: 'Carbon',       nameVi: 'Cacbon',     atomicMass: 12.011,  category: 'nonmetal',        block: 'p', period: 2, group: 14, gridRow: 2, gridCol: 14, electronConfig: '[He] 2s² 2p²',           protons: 6,   neutrons: 6,  electrons: 6,   meltingPoint: 3550,    boilingPoint: null,    density: 2.267,     electronegativity: 2.55, ionizationEnergy: 1086, electronAffinity: 121.8, atomicRadius: 77,  specificHeat: 0.709,  state: 'solid' },
  { atomicNumber: 7,  symbol: 'N',  name: 'Nitrogen',     nameVi: 'Nitơ',       atomicMass: 14.007,  category: 'nonmetal',        block: 'p', period: 2, group: 15, gridRow: 2, gridCol: 15, electronConfig: '[He] 2s² 2p³',           protons: 7,   neutrons: 7,  electrons: 7,   meltingPoint: -210.00, boilingPoint: -195.80, density: 0.001165,  electronegativity: 3.04, ionizationEnergy: 1402, electronAffinity: -7,    atomicRadius: 56,  specificHeat: 1.040,  state: 'gas' },
  { atomicNumber: 8,  symbol: 'O',  name: 'Oxygen',       nameVi: 'Oxi',        atomicMass: 15.999,  category: 'nonmetal',        block: 'p', period: 2, group: 16, gridRow: 2, gridCol: 16, electronConfig: '[He] 2s² 2p⁴',           protons: 8,   neutrons: 8,  electrons: 8,   meltingPoint: -218.80, boilingPoint: -183.00, density: 0.001331,  electronegativity: 3.44, ionizationEnergy: 1314, electronAffinity: 141,   atomicRadius: 48,  specificHeat: 0.919,  state: 'gas' },
  { atomicNumber: 9,  symbol: 'F',  name: 'Fluorine',     nameVi: 'Flo',        atomicMass: 18.998,  category: 'halogen',         block: 'p', period: 2, group: 17, gridRow: 2, gridCol: 17, electronConfig: '[He] 2s² 2p⁵',           protons: 9,   neutrons: 10, electrons: 9,   meltingPoint: -219.70, boilingPoint: -188.10, density: 0.001696,  electronegativity: 3.98, ionizationEnergy: 1681, electronAffinity: 328,   atomicRadius: 42,  specificHeat: 0.824,  state: 'gas' },
  { atomicNumber: 10, symbol: 'Ne', name: 'Neon',         nameVi: 'Neon',       atomicMass: 20.180,  category: 'noble-gas',       block: 'p', period: 2, group: 18, gridRow: 2, gridCol: 18, electronConfig: '[He] 2s² 2p⁶',           protons: 10,  neutrons: 10, electrons: 10,  meltingPoint: -248.60, boilingPoint: -246.10, density: 0.000839,  electronegativity: null, ionizationEnergy: 2081, electronAffinity: 0,     atomicRadius: 38,  specificHeat: 1.030,  state: 'gas' },
  // ─── Period 3 ───
  { atomicNumber: 11, symbol: 'Na', name: 'Sodium',       nameVi: 'Natri',      atomicMass: 22.990,  category: 'alkali-metal',    block: 's', period: 3, group: 1,  gridRow: 3, gridCol: 1,  electronConfig: '[Ne] 3s¹',               protons: 11,  neutrons: 12, electrons: 11,  meltingPoint: 97.80,   boilingPoint: 883,     density: 0.968,     electronegativity: 0.93, ionizationEnergy: 496,  electronAffinity: 52.8,  atomicRadius: 190, specificHeat: 1.228,  state: 'solid' },
  { atomicNumber: 12, symbol: 'Mg', name: 'Magnesium',    nameVi: 'Magiê',      atomicMass: 24.305,  category: 'alkaline-earth',  block: 's', period: 3, group: 2,  gridRow: 3, gridCol: 2,  electronConfig: '[Ne] 3s²',               protons: 12,  neutrons: 12, electrons: 12,  meltingPoint: 650,     boilingPoint: 1091,    density: 1.738,     electronegativity: 1.31, ionizationEnergy: 738,  electronAffinity: -40,   atomicRadius: 145, specificHeat: 1.023,  state: 'solid' },
  { atomicNumber: 13, symbol: 'Al', name: 'Aluminum',     nameVi: 'Nhôm',       atomicMass: 26.982,  category: 'post-transition', block: 'p', period: 3, group: 13, gridRow: 3, gridCol: 13, electronConfig: '[Ne] 3s² 3p¹',           protons: 13,  neutrons: 14, electrons: 13,  meltingPoint: 660.30,  boilingPoint: 2519,    density: 2.698,     electronegativity: 1.61, ionizationEnergy: 577,  electronAffinity: 42.5,  atomicRadius: 118, specificHeat: 0.900,  state: 'solid' },
  { atomicNumber: 14, symbol: 'Si', name: 'Silicon',      nameVi: 'Silic',      atomicMass: 28.086,  category: 'metalloid',       block: 'p', period: 3, group: 14, gridRow: 3, gridCol: 14, electronConfig: '[Ne] 3s² 3p²',           protons: 14,  neutrons: 14, electrons: 14,  meltingPoint: 1414,    boilingPoint: 3265,    density: 2.329,     electronegativity: 1.90, ionizationEnergy: 786,  electronAffinity: 134,   atomicRadius: 111, specificHeat: 0.705,  state: 'solid' },
  { atomicNumber: 15, symbol: 'P',  name: 'Phosphorus',   nameVi: 'Photpho',    atomicMass: 30.974,  category: 'nonmetal',        block: 'p', period: 3, group: 15, gridRow: 3, gridCol: 15, electronConfig: '[Ne] 3s² 3p³',           protons: 15,  neutrons: 16, electrons: 15,  meltingPoint: 44.20,   boilingPoint: 280.50,  density: 1.823,     electronegativity: 2.19, ionizationEnergy: 1012, electronAffinity: 72,    atomicRadius: 98,  specificHeat: 0.769,  state: 'solid' },
  { atomicNumber: 16, symbol: 'S',  name: 'Sulfur',       nameVi: 'Lưu huỳnh', atomicMass: 32.065,  category: 'nonmetal',        block: 'p', period: 3, group: 16, gridRow: 3, gridCol: 16, electronConfig: '[Ne] 3s² 3p⁴',           protons: 16,  neutrons: 16, electrons: 16,  meltingPoint: 115.20,  boilingPoint: 444.60,  density: 2.067,     electronegativity: 2.58, ionizationEnergy: 1000, electronAffinity: 200,   atomicRadius: 88,  specificHeat: 0.710,  state: 'solid' },
  { atomicNumber: 17, symbol: 'Cl', name: 'Chlorine',     nameVi: 'Clo',        atomicMass: 35.453,  category: 'halogen',         block: 'p', period: 3, group: 17, gridRow: 3, gridCol: 17, electronConfig: '[Ne] 3s² 3p⁵',           protons: 17,  neutrons: 18, electrons: 17,  meltingPoint: -101.50, boilingPoint: -34.00,  density: 0.00299,   electronegativity: 3.16, ionizationEnergy: 1251, electronAffinity: 349,   atomicRadius: 79,  specificHeat: 0.479,  state: 'gas' },
  { atomicNumber: 18, symbol: 'Ar', name: 'Argon',        nameVi: 'Argon',      atomicMass: 39.948,  category: 'noble-gas',       block: 'p', period: 3, group: 18, gridRow: 3, gridCol: 18, electronConfig: '[Ne] 3s² 3p⁶',           protons: 18,  neutrons: 22, electrons: 18,  meltingPoint: -189.30, boilingPoint: -185.80, density: 0.001633,  electronegativity: null, ionizationEnergy: 1521, electronAffinity: 0,     atomicRadius: 71,  specificHeat: 0.520,  state: 'gas' },
  // ─── Period 4 ───
  { atomicNumber: 19, symbol: 'K',  name: 'Potassium',    nameVi: 'Kali',       atomicMass: 39.098,  category: 'alkali-metal',    block: 's', period: 4, group: 1,  gridRow: 4, gridCol: 1,  electronConfig: '[Ar] 4s¹',               protons: 19,  neutrons: 20, electrons: 19,  meltingPoint: 63.50,   boilingPoint: 759,     density: 0.862,     electronegativity: 0.82, ionizationEnergy: 419,  electronAffinity: 48.4,  atomicRadius: 243, specificHeat: 0.757,  state: 'solid' },
  { atomicNumber: 20, symbol: 'Ca', name: 'Calcium',      nameVi: 'Canxi',      atomicMass: 40.078,  category: 'alkaline-earth',  block: 's', period: 4, group: 2,  gridRow: 4, gridCol: 2,  electronConfig: '[Ar] 4s²',               protons: 20,  neutrons: 20, electrons: 20,  meltingPoint: 842,     boilingPoint: 1484,    density: 1.55,      electronegativity: 1.00, ionizationEnergy: 590,  electronAffinity: 2.37,  atomicRadius: 194, specificHeat: 0.647,  state: 'solid' },
  { atomicNumber: 21, symbol: 'Sc', name: 'Scandium',     nameVi: 'Scandi',     atomicMass: 44.956,  category: 'transition-metal',block: 'd', period: 4, group: 3,  gridRow: 4, gridCol: 3,  electronConfig: '[Ar] 3d¹ 4s²',           protons: 21,  neutrons: 24, electrons: 21,  meltingPoint: 1541,    boilingPoint: 2836,    density: 2.985,     electronegativity: 1.36, ionizationEnergy: 633,  electronAffinity: 18.1,  atomicRadius: 170, specificHeat: 0.568,  state: 'solid' },
  { atomicNumber: 22, symbol: 'Ti', name: 'Titanium',     nameVi: 'Titan',      atomicMass: 47.867,  category: 'transition-metal',block: 'd', period: 4, group: 4,  gridRow: 4, gridCol: 4,  electronConfig: '[Ar] 3d² 4s²',           protons: 22,  neutrons: 26, electrons: 22,  meltingPoint: 1668,    boilingPoint: 3287,    density: 4.507,     electronegativity: 1.54, ionizationEnergy: 659,  electronAffinity: 7.6,   atomicRadius: 147, specificHeat: 0.520,  state: 'solid' },
  { atomicNumber: 23, symbol: 'V',  name: 'Vanadium',     nameVi: 'Vanadi',     atomicMass: 50.942,  category: 'transition-metal',block: 'd', period: 4, group: 5,  gridRow: 4, gridCol: 5,  electronConfig: '[Ar] 3d³ 4s²',           protons: 23,  neutrons: 28, electrons: 23,  meltingPoint: 1910,    boilingPoint: 3407,    density: 6.11,      electronegativity: 1.63, ionizationEnergy: 651,  electronAffinity: 50.6,  atomicRadius: 135, specificHeat: 0.489,  state: 'solid' },
  { atomicNumber: 24, symbol: 'Cr', name: 'Chromium',     nameVi: 'Crom',       atomicMass: 51.996,  category: 'transition-metal',block: 'd', period: 4, group: 6,  gridRow: 4, gridCol: 6,  electronConfig: '[Ar] 3d⁵ 4s¹',           protons: 24,  neutrons: 28, electrons: 24,  meltingPoint: 1907,    boilingPoint: 2671,    density: 7.15,      electronegativity: 1.66, ionizationEnergy: 653,  electronAffinity: 64.3,  atomicRadius: 129, specificHeat: 0.449,  state: 'solid' },
  { atomicNumber: 25, symbol: 'Mn', name: 'Manganese',    nameVi: 'Mangan',     atomicMass: 54.938,  category: 'transition-metal',block: 'd', period: 4, group: 7,  gridRow: 4, gridCol: 7,  electronConfig: '[Ar] 3d⁵ 4s²',           protons: 25,  neutrons: 30, electrons: 25,  meltingPoint: 1246,    boilingPoint: 2061,    density: 7.21,      electronegativity: 1.55, ionizationEnergy: 717,  electronAffinity: -50,   atomicRadius: 137, specificHeat: 0.479,  state: 'solid' },
  { atomicNumber: 26, symbol: 'Fe', name: 'Iron',         nameVi: 'Sắt',        atomicMass: 55.845,  category: 'transition-metal',block: 'd', period: 4, group: 8,  gridRow: 4, gridCol: 8,  electronConfig: '[Ar] 3d⁶ 4s²',           protons: 26,  neutrons: 30, electrons: 26,  meltingPoint: 1538,    boilingPoint: 2861,    density: 7.874,     electronegativity: 1.83, ionizationEnergy: 762,  electronAffinity: 15.7,  atomicRadius: 126, specificHeat: 0.449,  state: 'solid' },
  { atomicNumber: 27, symbol: 'Co', name: 'Cobalt',       nameVi: 'Coban',      atomicMass: 58.933,  category: 'transition-metal',block: 'd', period: 4, group: 9,  gridRow: 4, gridCol: 9,  electronConfig: '[Ar] 3d⁷ 4s²',           protons: 27,  neutrons: 32, electrons: 27,  meltingPoint: 1495,    boilingPoint: 2927,    density: 8.90,      electronegativity: 1.88, ionizationEnergy: 760,  electronAffinity: 63.7,  atomicRadius: 125, specificHeat: 0.421,  state: 'solid' },
  { atomicNumber: 28, symbol: 'Ni', name: 'Nickel',       nameVi: 'Niken',      atomicMass: 58.693,  category: 'transition-metal',block: 'd', period: 4, group: 10, gridRow: 4, gridCol: 10, electronConfig: '[Ar] 3d⁸ 4s²',           protons: 28,  neutrons: 31, electrons: 28,  meltingPoint: 1455,    boilingPoint: 2913,    density: 8.908,     electronegativity: 1.91, ionizationEnergy: 737,  electronAffinity: 112,   atomicRadius: 124, specificHeat: 0.444,  state: 'solid' },
  { atomicNumber: 29, symbol: 'Cu', name: 'Copper',       nameVi: 'Đồng',       atomicMass: 63.546,  category: 'transition-metal',block: 'd', period: 4, group: 11, gridRow: 4, gridCol: 11, electronConfig: '[Ar] 3d¹⁰ 4s¹',          protons: 29,  neutrons: 35, electrons: 29,  meltingPoint: 1084.60, boilingPoint: 2562,    density: 8.96,      electronegativity: 1.90, ionizationEnergy: 746,  electronAffinity: 118.4, atomicRadius: 128, specificHeat: 0.385,  state: 'solid' },
  { atomicNumber: 30, symbol: 'Zn', name: 'Zinc',         nameVi: 'Kẽm',        atomicMass: 65.380,  category: 'transition-metal',block: 'd', period: 4, group: 12, gridRow: 4, gridCol: 12, electronConfig: '[Ar] 3d¹⁰ 4s²',          protons: 30,  neutrons: 35, electrons: 30,  meltingPoint: 419.50,  boilingPoint: 907,     density: 7.14,      electronegativity: 1.65, ionizationEnergy: 906,  electronAffinity: -58,   atomicRadius: 137, specificHeat: 0.388,  state: 'solid' },
  { atomicNumber: 31, symbol: 'Ga', name: 'Gallium',      nameVi: 'Gali',       atomicMass: 69.723,  category: 'post-transition', block: 'p', period: 4, group: 13, gridRow: 4, gridCol: 13, electronConfig: '[Ar] 3d¹⁰ 4s² 4p¹',      protons: 31,  neutrons: 39, electrons: 31,  meltingPoint: 29.80,   boilingPoint: 2204,    density: 5.91,      electronegativity: 1.81, ionizationEnergy: 579,  electronAffinity: 28.9,  atomicRadius: 136, specificHeat: 0.371,  state: 'solid' },
  { atomicNumber: 32, symbol: 'Ge', name: 'Germanium',    nameVi: 'Germani',    atomicMass: 72.630,  category: 'metalloid',       block: 'p', period: 4, group: 14, gridRow: 4, gridCol: 14, electronConfig: '[Ar] 3d¹⁰ 4s² 4p²',      protons: 32,  neutrons: 41, electrons: 32,  meltingPoint: 938.30,  boilingPoint: 2833,    density: 5.323,     electronegativity: 2.01, ionizationEnergy: 762,  electronAffinity: 119,   atomicRadius: 125, specificHeat: 0.320,  state: 'solid' },
  { atomicNumber: 33, symbol: 'As', name: 'Arsenic',      nameVi: 'Asen',       atomicMass: 74.922,  category: 'metalloid',       block: 'p', period: 4, group: 15, gridRow: 4, gridCol: 15, electronConfig: '[Ar] 3d¹⁰ 4s² 4p³',      protons: 33,  neutrons: 42, electrons: 33,  meltingPoint: 817,     boilingPoint: null,    density: 5.727,     electronegativity: 2.18, ionizationEnergy: 947,  electronAffinity: 78,    atomicRadius: 114, specificHeat: 0.329,  state: 'solid' },
  { atomicNumber: 34, symbol: 'Se', name: 'Selenium',     nameVi: 'Selen',      atomicMass: 78.971,  category: 'nonmetal',        block: 'p', period: 4, group: 16, gridRow: 4, gridCol: 16, electronConfig: '[Ar] 3d¹⁰ 4s² 4p⁴',      protons: 34,  neutrons: 45, electrons: 34,  meltingPoint: 221,     boilingPoint: 685,     density: 4.819,     electronegativity: 2.55, ionizationEnergy: 941,  electronAffinity: 195,   atomicRadius: 103, specificHeat: 0.321,  state: 'solid' },
  { atomicNumber: 35, symbol: 'Br', name: 'Bromine',      nameVi: 'Brom',       atomicMass: 79.904,  category: 'halogen',         block: 'p', period: 4, group: 17, gridRow: 4, gridCol: 17, electronConfig: '[Ar] 3d¹⁰ 4s² 4p⁵',      protons: 35,  neutrons: 45, electrons: 35,  meltingPoint: -7.20,   boilingPoint: 58.90,   density: 3.102,     electronegativity: 2.96, ionizationEnergy: 1140, electronAffinity: 324.6, atomicRadius: 94,  specificHeat: 0.474,  state: 'liquid' },
  { atomicNumber: 36, symbol: 'Kr', name: 'Krypton',      nameVi: 'Krypton',    atomicMass: 83.798,  category: 'noble-gas',       block: 'p', period: 4, group: 18, gridRow: 4, gridCol: 18, electronConfig: '[Ar] 3d¹⁰ 4s² 4p⁶',      protons: 36,  neutrons: 48, electrons: 36,  meltingPoint: -157.40, boilingPoint: -153.20, density: 0.003478,  electronegativity: 3.00, ionizationEnergy: 1351, electronAffinity: 0,     atomicRadius: 88,  specificHeat: 0.248,  state: 'gas' },
  // ─── Period 5 ───
  { atomicNumber: 37, symbol: 'Rb', name: 'Rubidium',     nameVi: 'Rubidi',     atomicMass: 85.468,  category: 'alkali-metal',    block: 's', period: 5, group: 1,  gridRow: 5, gridCol: 1,  electronConfig: '[Kr] 5s¹',               protons: 37,  neutrons: 48, electrons: 37,  meltingPoint: 39.30,   boilingPoint: 688,     density: 1.532,     electronegativity: 0.82, ionizationEnergy: 403,  electronAffinity: 46.9,  atomicRadius: 265, specificHeat: 0.363,  state: 'solid' },
  { atomicNumber: 38, symbol: 'Sr', name: 'Strontium',    nameVi: 'Stronti',    atomicMass: 87.620,  category: 'alkaline-earth',  block: 's', period: 5, group: 2,  gridRow: 5, gridCol: 2,  electronConfig: '[Kr] 5s²',               protons: 38,  neutrons: 50, electrons: 38,  meltingPoint: 777,     boilingPoint: 1382,    density: 2.64,      electronegativity: 0.95, ionizationEnergy: 550,  electronAffinity: 5.03,  atomicRadius: 219, specificHeat: 0.301,  state: 'solid' },
  { atomicNumber: 39, symbol: 'Y',  name: 'Yttrium',      nameVi: 'Ytri',       atomicMass: 88.906,  category: 'transition-metal',block: 'd', period: 5, group: 3,  gridRow: 5, gridCol: 3,  electronConfig: '[Kr] 4d¹ 5s²',           protons: 39,  neutrons: 50, electrons: 39,  meltingPoint: 1522,    boilingPoint: 3345,    density: 4.47,      electronegativity: 1.22, ionizationEnergy: 600,  electronAffinity: 29.6,  atomicRadius: 190, specificHeat: 0.298,  state: 'solid' },
  { atomicNumber: 40, symbol: 'Zr', name: 'Zirconium',    nameVi: 'Ziriconi',   atomicMass: 91.224,  category: 'transition-metal',block: 'd', period: 5, group: 4,  gridRow: 5, gridCol: 4,  electronConfig: '[Kr] 4d² 5s²',           protons: 40,  neutrons: 51, electrons: 40,  meltingPoint: 1855,    boilingPoint: 4409,    density: 6.52,      electronegativity: 1.33, ionizationEnergy: 640,  electronAffinity: 41.1,  atomicRadius: 175, specificHeat: 0.278,  state: 'solid' },
  { atomicNumber: 41, symbol: 'Nb', name: 'Niobium',      nameVi: 'Niobi',      atomicMass: 92.906,  category: 'transition-metal',block: 'd', period: 5, group: 5,  gridRow: 5, gridCol: 5,  electronConfig: '[Kr] 4d⁴ 5s¹',           protons: 41,  neutrons: 52, electrons: 41,  meltingPoint: 2477,    boilingPoint: 4744,    density: 8.57,      electronegativity: 1.60, ionizationEnergy: 652,  electronAffinity: 86.1,  atomicRadius: 164, specificHeat: 0.265,  state: 'solid' },
  { atomicNumber: 42, symbol: 'Mo', name: 'Molybdenum',   nameVi: 'Molipđen',   atomicMass: 95.960,  category: 'transition-metal',block: 'd', period: 5, group: 6,  gridRow: 5, gridCol: 6,  electronConfig: '[Kr] 4d⁵ 5s¹',           protons: 42,  neutrons: 54, electrons: 42,  meltingPoint: 2623,    boilingPoint: 4639,    density: 10.28,     electronegativity: 2.16, ionizationEnergy: 684,  electronAffinity: 71.9,  atomicRadius: 154, specificHeat: 0.251,  state: 'solid' },
  { atomicNumber: 43, symbol: 'Tc', name: 'Technetium',   nameVi: 'Tecneti',    atomicMass: 98.000,  category: 'transition-metal',block: 'd', period: 5, group: 7,  gridRow: 5, gridCol: 7,  electronConfig: '[Kr] 4d⁵ 5s²',           protons: 43,  neutrons: 55, electrons: 43,  meltingPoint: 2157,    boilingPoint: 4265,    density: 11.50,     electronegativity: 1.90, ionizationEnergy: 702,  electronAffinity: 53,    atomicRadius: 147, specificHeat: 0.210,  state: 'solid' },
  { atomicNumber: 44, symbol: 'Ru', name: 'Ruthenium',    nameVi: 'Rutheni',    atomicMass: 101.07,  category: 'transition-metal',block: 'd', period: 5, group: 8,  gridRow: 5, gridCol: 8,  electronConfig: '[Kr] 4d⁷ 5s¹',           protons: 44,  neutrons: 57, electrons: 44,  meltingPoint: 2334,    boilingPoint: 4150,    density: 12.37,     electronegativity: 2.20, ionizationEnergy: 710,  electronAffinity: 101.3, atomicRadius: 146, specificHeat: 0.238,  state: 'solid' },
  { atomicNumber: 45, symbol: 'Rh', name: 'Rhodium',      nameVi: 'Rhodi',      atomicMass: 102.906, category: 'transition-metal',block: 'd', period: 5, group: 9,  gridRow: 5, gridCol: 9,  electronConfig: '[Kr] 4d⁸ 5s¹',           protons: 45,  neutrons: 58, electrons: 45,  meltingPoint: 1964,    boilingPoint: 3695,    density: 12.41,     electronegativity: 2.28, ionizationEnergy: 720,  electronAffinity: 109.7, atomicRadius: 142, specificHeat: 0.243,  state: 'solid' },
  { atomicNumber: 46, symbol: 'Pd', name: 'Palladium',    nameVi: 'Palladi',    atomicMass: 106.420, category: 'transition-metal',block: 'd', period: 5, group: 10, gridRow: 5, gridCol: 10, electronConfig: '[Kr] 4d¹⁰',              protons: 46,  neutrons: 60, electrons: 46,  meltingPoint: 1555,    boilingPoint: 2963,    density: 12.02,     electronegativity: 2.20, ionizationEnergy: 805,  electronAffinity: 53.7,  atomicRadius: 139, specificHeat: 0.244,  state: 'solid' },
  { atomicNumber: 47, symbol: 'Ag', name: 'Silver',       nameVi: 'Bạc',        atomicMass: 107.868, category: 'transition-metal',block: 'd', period: 5, group: 11, gridRow: 5, gridCol: 11, electronConfig: '[Kr] 4d¹⁰ 5s¹',          protons: 47,  neutrons: 61, electrons: 47,  meltingPoint: 961.80,  boilingPoint: 2162,    density: 10.49,     electronegativity: 1.93, ionizationEnergy: 731,  electronAffinity: 125.6, atomicRadius: 165, specificHeat: 0.235,  state: 'solid' },
  { atomicNumber: 48, symbol: 'Cd', name: 'Cadmium',      nameVi: 'Cadmi',      atomicMass: 112.414, category: 'transition-metal',block: 'd', period: 5, group: 12, gridRow: 5, gridCol: 12, electronConfig: '[Kr] 4d¹⁰ 5s²',          protons: 48,  neutrons: 64, electrons: 48,  meltingPoint: 321.10,  boilingPoint: 767,     density: 8.65,      electronegativity: 1.69, ionizationEnergy: 868,  electronAffinity: -68,   atomicRadius: 161, specificHeat: 0.232,  state: 'solid' },
  { atomicNumber: 49, symbol: 'In', name: 'Indium',       nameVi: 'Indi',       atomicMass: 114.818, category: 'post-transition', block: 'p', period: 5, group: 13, gridRow: 5, gridCol: 13, electronConfig: '[Kr] 4d¹⁰ 5s² 5p¹',      protons: 49,  neutrons: 66, electrons: 49,  meltingPoint: 156.60,  boilingPoint: 2072,    density: 7.31,      electronegativity: 1.78, ionizationEnergy: 558,  electronAffinity: 28.9,  atomicRadius: 167, specificHeat: 0.233,  state: 'solid' },
  { atomicNumber: 50, symbol: 'Sn', name: 'Tin',          nameVi: 'Thiếc',      atomicMass: 118.710, category: 'post-transition', block: 'p', period: 5, group: 14, gridRow: 5, gridCol: 14, electronConfig: '[Kr] 4d¹⁰ 5s² 5p²',      protons: 50,  neutrons: 69, electrons: 50,  meltingPoint: 231.90,  boilingPoint: 2602,    density: 7.287,     electronegativity: 1.96, ionizationEnergy: 709,  electronAffinity: 107.3, atomicRadius: 145, specificHeat: 0.228,  state: 'solid' },
  { atomicNumber: 51, symbol: 'Sb', name: 'Antimony',     nameVi: 'Antimon',    atomicMass: 121.760, category: 'metalloid',       block: 'p', period: 5, group: 15, gridRow: 5, gridCol: 15, electronConfig: '[Kr] 4d¹⁰ 5s² 5p³',      protons: 51,  neutrons: 71, electrons: 51,  meltingPoint: 630.60,  boilingPoint: 1587,    density: 6.697,     electronegativity: 2.05, ionizationEnergy: 834,  electronAffinity: 101,   atomicRadius: 133, specificHeat: 0.207,  state: 'solid' },
  { atomicNumber: 52, symbol: 'Te', name: 'Tellurium',    nameVi: 'Telua',      atomicMass: 127.600, category: 'metalloid',       block: 'p', period: 5, group: 16, gridRow: 5, gridCol: 16, electronConfig: '[Kr] 4d¹⁰ 5s² 5p⁴',      protons: 52,  neutrons: 76, electrons: 52,  meltingPoint: 449.50,  boilingPoint: 988,     density: 6.24,      electronegativity: 2.10, ionizationEnergy: 869,  electronAffinity: 190.2, atomicRadius: 123, specificHeat: 0.202,  state: 'solid' },
  { atomicNumber: 53, symbol: 'I',  name: 'Iodine',       nameVi: 'Iot',        atomicMass: 126.904, category: 'halogen',         block: 'p', period: 5, group: 17, gridRow: 5, gridCol: 17, electronConfig: '[Kr] 4d¹⁰ 5s² 5p⁵',      protons: 53,  neutrons: 74, electrons: 53,  meltingPoint: 113.70,  boilingPoint: 184.30,  density: 4.933,     electronegativity: 2.66, ionizationEnergy: 1008, electronAffinity: 295.2, atomicRadius: 115, specificHeat: 0.214,  state: 'solid' },
  { atomicNumber: 54, symbol: 'Xe', name: 'Xenon',        nameVi: 'Xenon',      atomicMass: 131.293, category: 'noble-gas',       block: 'p', period: 5, group: 18, gridRow: 5, gridCol: 18, electronConfig: '[Kr] 4d¹⁰ 5s² 5p⁶',      protons: 54,  neutrons: 77, electrons: 54,  meltingPoint: -111.80, boilingPoint: -108.00, density: 0.005458,  electronegativity: 2.60, ionizationEnergy: 1170, electronAffinity: 0,     atomicRadius: 108, specificHeat: 0.158,  state: 'gas' },
  // ─── Period 6 ───
  { atomicNumber: 55, symbol: 'Cs', name: 'Cesium',       nameVi: 'Xesi',       atomicMass: 132.905, category: 'alkali-metal',    block: 's', period: 6, group: 1,  gridRow: 6, gridCol: 1,  electronConfig: '[Xe] 6s¹',               protons: 55,  neutrons: 78, electrons: 55,  meltingPoint: 28.50,   boilingPoint: 671,     density: 1.873,     electronegativity: 0.79, ionizationEnergy: 376,  electronAffinity: 45.5,  atomicRadius: 298, specificHeat: 0.242,  state: 'solid' },
  { atomicNumber: 56, symbol: 'Ba', name: 'Barium',       nameVi: 'Bari',       atomicMass: 137.327, category: 'alkaline-earth',  block: 's', period: 6, group: 2,  gridRow: 6, gridCol: 2,  electronConfig: '[Xe] 6s²',               protons: 56,  neutrons: 81, electrons: 56,  meltingPoint: 727,     boilingPoint: 1870,    density: 3.62,      electronegativity: 0.89, ionizationEnergy: 503,  electronAffinity: 13.95, atomicRadius: 253, specificHeat: 0.204,  state: 'solid' },
  // Lanthanides (gridRow 9)
  { atomicNumber: 57, symbol: 'La', name: 'Lanthanum',    nameVi: 'Lantan',     atomicMass: 138.905, category: 'lanthanide',      block: 'f', period: 6, group: null, gridRow: 9, gridCol: 3,  electronConfig: '[Xe] 5d¹ 6s²',           protons: 57,  neutrons: 82, electrons: 57,  meltingPoint: 918,     boilingPoint: 3464,    density: 6.162,     electronegativity: 1.10, ionizationEnergy: 538,  electronAffinity: 48,    atomicRadius: 195, specificHeat: 0.195,  state: 'solid' },
  { atomicNumber: 58, symbol: 'Ce', name: 'Cerium',       nameVi: 'Xeri',       atomicMass: 140.116, category: 'lanthanide',      block: 'f', period: 6, group: null, gridRow: 9, gridCol: 4,  electronConfig: '[Xe] 4f¹ 5d¹ 6s²',       protons: 58,  neutrons: 82, electrons: 58,  meltingPoint: 798,     boilingPoint: 3443,    density: 6.770,     electronegativity: 1.12, ionizationEnergy: 534,  electronAffinity: 50,    atomicRadius: 185, specificHeat: 0.192,  state: 'solid' },
  { atomicNumber: 59, symbol: 'Pr', name: 'Praseodymium', nameVi: 'Praseodymi', atomicMass: 140.908, category: 'lanthanide',      block: 'f', period: 6, group: null, gridRow: 9, gridCol: 5,  electronConfig: '[Xe] 4f³ 6s²',           protons: 59,  neutrons: 82, electrons: 59,  meltingPoint: 931,     boilingPoint: 3520,    density: 6.77,      electronegativity: 1.13, ionizationEnergy: 527,  electronAffinity: 50,    atomicRadius: 185, specificHeat: 0.193,  state: 'solid' },
  { atomicNumber: 60, symbol: 'Nd', name: 'Neodymium',    nameVi: 'Neodymi',    atomicMass: 144.242, category: 'lanthanide',      block: 'f', period: 6, group: null, gridRow: 9, gridCol: 6,  electronConfig: '[Xe] 4f⁴ 6s²',           protons: 60,  neutrons: 84, electrons: 60,  meltingPoint: 1016,    boilingPoint: 3074,    density: 7.01,      electronegativity: 1.14, ionizationEnergy: 533,  electronAffinity: 50,    atomicRadius: 185, specificHeat: 0.190,  state: 'solid' },
  { atomicNumber: 61, symbol: 'Pm', name: 'Promethium',   nameVi: 'Prometi',    atomicMass: 145.000, category: 'lanthanide',      block: 'f', period: 6, group: null, gridRow: 9, gridCol: 7,  electronConfig: '[Xe] 4f⁵ 6s²',           protons: 61,  neutrons: 84, electrons: 61,  meltingPoint: 1042,    boilingPoint: 3000,    density: 7.26,      electronegativity: 1.13, ionizationEnergy: 540,  electronAffinity: 50,    atomicRadius: 185, specificHeat: null,   state: 'solid' },
  { atomicNumber: 62, symbol: 'Sm', name: 'Samarium',     nameVi: 'Samari',     atomicMass: 150.360, category: 'lanthanide',      block: 'f', period: 6, group: null, gridRow: 9, gridCol: 8,  electronConfig: '[Xe] 4f⁶ 6s²',           protons: 62,  neutrons: 88, electrons: 62,  meltingPoint: 1072,    boilingPoint: 1794,    density: 7.52,      electronegativity: 1.17, ionizationEnergy: 543,  electronAffinity: 50,    atomicRadius: 185, specificHeat: 0.197,  state: 'solid' },
  { atomicNumber: 63, symbol: 'Eu', name: 'Europium',     nameVi: 'Europi',     atomicMass: 151.964, category: 'lanthanide',      block: 'f', period: 6, group: null, gridRow: 9, gridCol: 9,  electronConfig: '[Xe] 4f⁷ 6s²',           protons: 63,  neutrons: 89, electrons: 63,  meltingPoint: 822,     boilingPoint: 1596,    density: 5.24,      electronegativity: 1.20, ionizationEnergy: 547,  electronAffinity: 50,    atomicRadius: 185, specificHeat: 0.182,  state: 'solid' },
  { atomicNumber: 64, symbol: 'Gd', name: 'Gadolinium',   nameVi: 'Gadolini',   atomicMass: 157.250, category: 'lanthanide',      block: 'f', period: 6, group: null, gridRow: 9, gridCol: 10, electronConfig: '[Xe] 4f⁷ 5d¹ 6s²',       protons: 64,  neutrons: 93, electrons: 64,  meltingPoint: 1312,    boilingPoint: 3273,    density: 7.90,      electronegativity: 1.20, ionizationEnergy: 593,  electronAffinity: 50,    atomicRadius: 180, specificHeat: 0.236,  state: 'solid' },
  { atomicNumber: 65, symbol: 'Tb', name: 'Terbium',      nameVi: 'Terbi',      atomicMass: 158.925, category: 'lanthanide',      block: 'f', period: 6, group: null, gridRow: 9, gridCol: 11, electronConfig: '[Xe] 4f⁹ 6s²',           protons: 65,  neutrons: 94, electrons: 65,  meltingPoint: 1356,    boilingPoint: 3230,    density: 8.23,      electronegativity: 1.20, ionizationEnergy: 566,  electronAffinity: 50,    atomicRadius: 175, specificHeat: 0.182,  state: 'solid' },
  { atomicNumber: 66, symbol: 'Dy', name: 'Dysprosium',   nameVi: 'Dysprosi',   atomicMass: 162.500, category: 'lanthanide',      block: 'f', period: 6, group: null, gridRow: 9, gridCol: 12, electronConfig: '[Xe] 4f¹⁰ 6s²',          protons: 66,  neutrons: 97, electrons: 66,  meltingPoint: 1412,    boilingPoint: 2567,    density: 8.55,      electronegativity: 1.22, ionizationEnergy: 573,  electronAffinity: 50,    atomicRadius: 175, specificHeat: 0.170,  state: 'solid' },
  { atomicNumber: 67, symbol: 'Ho', name: 'Holmium',      nameVi: 'Holmi',      atomicMass: 164.930, category: 'lanthanide',      block: 'f', period: 6, group: null, gridRow: 9, gridCol: 13, electronConfig: '[Xe] 4f¹¹ 6s²',          protons: 67,  neutrons: 98, electrons: 67,  meltingPoint: 1474,    boilingPoint: 2700,    density: 8.80,      electronegativity: 1.23, ionizationEnergy: 581,  electronAffinity: 50,    atomicRadius: 175, specificHeat: 0.165,  state: 'solid' },
  { atomicNumber: 68, symbol: 'Er', name: 'Erbium',       nameVi: 'Erbi',       atomicMass: 167.259, category: 'lanthanide',      block: 'f', period: 6, group: null, gridRow: 9, gridCol: 14, electronConfig: '[Xe] 4f¹² 6s²',          protons: 68,  neutrons: 99, electrons: 68,  meltingPoint: 1529,    boilingPoint: 2868,    density: 9.07,      electronegativity: 1.24, ionizationEnergy: 589,  electronAffinity: 50,    atomicRadius: 175, specificHeat: 0.168,  state: 'solid' },
  { atomicNumber: 69, symbol: 'Tm', name: 'Thulium',      nameVi: 'Thuli',      atomicMass: 168.934, category: 'lanthanide',      block: 'f', period: 6, group: null, gridRow: 9, gridCol: 15, electronConfig: '[Xe] 4f¹³ 6s²',          protons: 69,  neutrons: 100,electrons: 69,  meltingPoint: 1545,    boilingPoint: 1950,    density: 9.32,      electronegativity: 1.25, ionizationEnergy: 597,  electronAffinity: 50,    atomicRadius: 175, specificHeat: 0.160,  state: 'solid' },
  { atomicNumber: 70, symbol: 'Yb', name: 'Ytterbium',    nameVi: 'Ytterbi',    atomicMass: 173.054, category: 'lanthanide',      block: 'f', period: 6, group: null, gridRow: 9, gridCol: 16, electronConfig: '[Xe] 4f¹⁴ 6s²',          protons: 70,  neutrons: 103,electrons: 70,  meltingPoint: 819,     boilingPoint: 1196,    density: 6.90,      electronegativity: 1.10, ionizationEnergy: 603,  electronAffinity: 50,    atomicRadius: 175, specificHeat: 0.155,  state: 'solid' },
  { atomicNumber: 71, symbol: 'Lu', name: 'Lutetium',     nameVi: 'Luteti',     atomicMass: 174.967, category: 'lanthanide',      block: 'f', period: 6, group: null, gridRow: 9, gridCol: 17, electronConfig: '[Xe] 4f¹⁴ 5d¹ 6s²',      protons: 71,  neutrons: 104,electrons: 71,  meltingPoint: 1663,    boilingPoint: 3402,    density: 9.84,      electronegativity: 1.27, ionizationEnergy: 524,  electronAffinity: 50,    atomicRadius: 175, specificHeat: 0.154,  state: 'solid' },
  // Period 6 d-block (after lanthanide gap)
  { atomicNumber: 72, symbol: 'Hf', name: 'Hafnium',      nameVi: 'Hafni',      atomicMass: 178.490, category: 'transition-metal',block: 'd', period: 6, group: 4,  gridRow: 6, gridCol: 4,  electronConfig: '[Xe] 4f¹⁴ 5d² 6s²',      protons: 72,  neutrons: 106,electrons: 72,  meltingPoint: 2233,    boilingPoint: 4603,    density: 13.31,     electronegativity: 1.30, ionizationEnergy: 659,  electronAffinity: 0,     atomicRadius: 167, specificHeat: 0.144,  state: 'solid' },
  { atomicNumber: 73, symbol: 'Ta', name: 'Tantalum',     nameVi: 'Tantali',    atomicMass: 180.948, category: 'transition-metal',block: 'd', period: 6, group: 5,  gridRow: 6, gridCol: 5,  electronConfig: '[Xe] 4f¹⁴ 5d³ 6s²',      protons: 73,  neutrons: 108,electrons: 73,  meltingPoint: 3017,    boilingPoint: 5458,    density: 16.69,     electronegativity: 1.50, ionizationEnergy: 761,  electronAffinity: 31,    atomicRadius: 149, specificHeat: 0.140,  state: 'solid' },
  { atomicNumber: 74, symbol: 'W',  name: 'Tungsten',     nameVi: 'Vonfram',    atomicMass: 183.840, category: 'transition-metal',block: 'd', period: 6, group: 6,  gridRow: 6, gridCol: 6,  electronConfig: '[Xe] 4f¹⁴ 5d⁴ 6s²',      protons: 74,  neutrons: 110,electrons: 74,  meltingPoint: 3422,    boilingPoint: 5555,    density: 19.25,     electronegativity: 2.36, ionizationEnergy: 770,  electronAffinity: 78.6,  atomicRadius: 141, specificHeat: 0.132,  state: 'solid' },
  { atomicNumber: 75, symbol: 'Re', name: 'Rhenium',      nameVi: 'Rheni',      atomicMass: 186.207, category: 'transition-metal',block: 'd', period: 6, group: 7,  gridRow: 6, gridCol: 7,  electronConfig: '[Xe] 4f¹⁴ 5d⁵ 6s²',      protons: 75,  neutrons: 111,electrons: 75,  meltingPoint: 3186,    boilingPoint: 5596,    density: 21.02,     electronegativity: 1.90, ionizationEnergy: 760,  electronAffinity: 14.5,  atomicRadius: 137, specificHeat: 0.137,  state: 'solid' },
  { atomicNumber: 76, symbol: 'Os', name: 'Osmium',       nameVi: 'Osmi',       atomicMass: 190.230, category: 'transition-metal',block: 'd', period: 6, group: 8,  gridRow: 6, gridCol: 8,  electronConfig: '[Xe] 4f¹⁴ 5d⁶ 6s²',      protons: 76,  neutrons: 114,electrons: 76,  meltingPoint: 3033,    boilingPoint: 5012,    density: 22.59,     electronegativity: 2.20, ionizationEnergy: 840,  electronAffinity: 106.1, atomicRadius: 135, specificHeat: 0.130,  state: 'solid' },
  { atomicNumber: 77, symbol: 'Ir', name: 'Iridium',      nameVi: 'Iridi',      atomicMass: 192.217, category: 'transition-metal',block: 'd', period: 6, group: 9,  gridRow: 6, gridCol: 9,  electronConfig: '[Xe] 4f¹⁴ 5d⁷ 6s²',      protons: 77,  neutrons: 115,electrons: 77,  meltingPoint: 2446,    boilingPoint: 4428,    density: 22.56,     electronegativity: 2.20, ionizationEnergy: 880,  electronAffinity: 151,   atomicRadius: 136, specificHeat: 0.131,  state: 'solid' },
  { atomicNumber: 78, symbol: 'Pt', name: 'Platinum',     nameVi: 'Platin',     atomicMass: 195.084, category: 'transition-metal',block: 'd', period: 6, group: 10, gridRow: 6, gridCol: 10, electronConfig: '[Xe] 4f¹⁴ 5d⁹ 6s¹',      protons: 78,  neutrons: 117,electrons: 78,  meltingPoint: 1768.40, boilingPoint: 3825,    density: 21.45,     electronegativity: 2.28, ionizationEnergy: 870,  electronAffinity: 205.3, atomicRadius: 139, specificHeat: 0.133,  state: 'solid' },
  { atomicNumber: 79, symbol: 'Au', name: 'Gold',         nameVi: 'Vàng',       atomicMass: 196.967, category: 'transition-metal',block: 'd', period: 6, group: 11, gridRow: 6, gridCol: 11, electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s¹',     protons: 79,  neutrons: 118,electrons: 79,  meltingPoint: 1064.20, boilingPoint: 2856,    density: 19.32,     electronegativity: 2.54, ionizationEnergy: 890,  electronAffinity: 222.8, atomicRadius: 144, specificHeat: 0.129,  state: 'solid' },
  { atomicNumber: 80, symbol: 'Hg', name: 'Mercury',      nameVi: 'Thủy ngân', atomicMass: 200.592, category: 'transition-metal',block: 'd', period: 6, group: 12, gridRow: 6, gridCol: 12, electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s²',     protons: 80,  neutrons: 121,electrons: 80,  meltingPoint: -38.80,  boilingPoint: 356.70,  density: 13.534,    electronegativity: 2.00, ionizationEnergy: 1007, electronAffinity: -48,   atomicRadius: 151, specificHeat: 0.140,  state: 'liquid' },
  { atomicNumber: 81, symbol: 'Tl', name: 'Thallium',     nameVi: 'Tali',       atomicMass: 204.380, category: 'post-transition', block: 'p', period: 6, group: 13, gridRow: 6, gridCol: 13, electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹', protons: 81,  neutrons: 123,electrons: 81,  meltingPoint: 304,     boilingPoint: 1473,    density: 11.85,     electronegativity: 1.62, ionizationEnergy: 589,  electronAffinity: 19.2,  atomicRadius: 170, specificHeat: 0.129,  state: 'solid' },
  { atomicNumber: 82, symbol: 'Pb', name: 'Lead',         nameVi: 'Chì',        atomicMass: 207.200, category: 'post-transition', block: 'p', period: 6, group: 14, gridRow: 6, gridCol: 14, electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²', protons: 82,  neutrons: 125,electrons: 82,  meltingPoint: 327.50,  boilingPoint: 1749,    density: 11.34,     electronegativity: 2.33, ionizationEnergy: 716,  electronAffinity: 35.1,  atomicRadius: 175, specificHeat: 0.128,  state: 'solid' },
  { atomicNumber: 83, symbol: 'Bi', name: 'Bismuth',      nameVi: 'Bismut',     atomicMass: 208.980, category: 'post-transition', block: 'p', period: 6, group: 15, gridRow: 6, gridCol: 15, electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³', protons: 83,  neutrons: 126,electrons: 83,  meltingPoint: 271.50,  boilingPoint: 1564,    density: 9.747,     electronegativity: 2.02, ionizationEnergy: 703,  electronAffinity: 91.2,  atomicRadius: 170, specificHeat: 0.122,  state: 'solid' },
  { atomicNumber: 84, symbol: 'Po', name: 'Polonium',     nameVi: 'Poloni',     atomicMass: 209.000, category: 'metalloid',       block: 'p', period: 6, group: 16, gridRow: 6, gridCol: 16, electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴', protons: 84,  neutrons: 125,electrons: 84,  meltingPoint: 254,     boilingPoint: 962,     density: 9.32,      electronegativity: 2.00, ionizationEnergy: 812,  electronAffinity: 183.3, atomicRadius: 168, specificHeat: null,   state: 'solid' },
  { atomicNumber: 85, symbol: 'At', name: 'Astatine',     nameVi: 'Astatin',    atomicMass: 210.000, category: 'halogen',         block: 'p', period: 6, group: 17, gridRow: 6, gridCol: 17, electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵', protons: 85,  neutrons: 125,electrons: 85,  meltingPoint: 302,     boilingPoint: 337,     density: 7.00,      electronegativity: 2.20, ionizationEnergy: 899,  electronAffinity: 270.1, atomicRadius: 150, specificHeat: null,   state: 'solid' },
  { atomicNumber: 86, symbol: 'Rn', name: 'Radon',        nameVi: 'Radon',      atomicMass: 222.000, category: 'noble-gas',       block: 'p', period: 6, group: 18, gridRow: 6, gridCol: 18, electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶', protons: 86,  neutrons: 136,electrons: 86,  meltingPoint: -71.15,  boilingPoint: -61.70,  density: 0.00973,   electronegativity: null, ionizationEnergy: 1037, electronAffinity: 0,     atomicRadius: 120, specificHeat: 0.094,  state: 'gas' },
  // ─── Period 7 ───
  { atomicNumber: 87, symbol: 'Fr', name: 'Francium',     nameVi: 'Franxi',     atomicMass: 223.000, category: 'alkali-metal',    block: 's', period: 7, group: 1,  gridRow: 7, gridCol: 1,  electronConfig: '[Rn] 7s¹',               protons: 87,  neutrons: 136,electrons: 87,  meltingPoint: 27,      boilingPoint: 677,     density: 1.87,      electronegativity: 0.70, ionizationEnergy: 380,  electronAffinity: 44,    atomicRadius: 348, specificHeat: null,   state: 'solid' },
  { atomicNumber: 88, symbol: 'Ra', name: 'Radium',       nameVi: 'Radi',       atomicMass: 226.000, category: 'alkaline-earth',  block: 's', period: 7, group: 2,  gridRow: 7, gridCol: 2,  electronConfig: '[Rn] 7s²',               protons: 88,  neutrons: 138,electrons: 88,  meltingPoint: 700,     boilingPoint: 1737,    density: 5.00,      electronegativity: 0.90, ionizationEnergy: 509,  electronAffinity: 10,    atomicRadius: 283, specificHeat: 0.094,  state: 'solid' },
  // Actinides (gridRow 10)
  { atomicNumber: 89,  symbol: 'Ac', name: 'Actinium',     nameVi: 'Actini',     atomicMass: 227.000, category: 'actinide',        block: 'f', period: 7, group: null, gridRow: 10, gridCol: 3,  electronConfig: '[Rn] 6d¹ 7s²',           protons: 89,  neutrons: 138,electrons: 89,  meltingPoint: 1051,    boilingPoint: 3198,    density: 10.07,     electronegativity: 1.10, ionizationEnergy: 499,  electronAffinity: 33,    atomicRadius: 195, specificHeat: 0.120,  state: 'solid' },
  { atomicNumber: 90,  symbol: 'Th', name: 'Thorium',      nameVi: 'Thori',      atomicMass: 232.038, category: 'actinide',        block: 'f', period: 7, group: null, gridRow: 10, gridCol: 4,  electronConfig: '[Rn] 6d² 7s²',           protons: 90,  neutrons: 142,electrons: 90,  meltingPoint: 1750,    boilingPoint: 4820,    density: 11.724,    electronegativity: 1.30, ionizationEnergy: 587,  electronAffinity: 112.8, atomicRadius: 179, specificHeat: 0.113,  state: 'solid' },
  { atomicNumber: 91,  symbol: 'Pa', name: 'Protactinium', nameVi: 'Protactini', atomicMass: 231.036, category: 'actinide',        block: 'f', period: 7, group: null, gridRow: 10, gridCol: 5,  electronConfig: '[Rn] 5f² 6d¹ 7s²',       protons: 91,  neutrons: 140,electrons: 91,  meltingPoint: 1568,    boilingPoint: 4027,    density: 15.37,     electronegativity: 1.50, ionizationEnergy: 568,  electronAffinity: null,  atomicRadius: 163, specificHeat: null,   state: 'solid' },
  { atomicNumber: 92,  symbol: 'U',  name: 'Uranium',      nameVi: 'Urani',      atomicMass: 238.029, category: 'actinide',        block: 'f', period: 7, group: null, gridRow: 10, gridCol: 6,  electronConfig: '[Rn] 5f³ 6d¹ 7s²',       protons: 92,  neutrons: 146,electrons: 92,  meltingPoint: 1135,    boilingPoint: 3818,    density: 19.05,     electronegativity: 1.38, ionizationEnergy: 598,  electronAffinity: 50.9,  atomicRadius: 156, specificHeat: 0.116,  state: 'solid' },
  { atomicNumber: 93,  symbol: 'Np', name: 'Neptunium',    nameVi: 'Neptuni',    atomicMass: 237.000, category: 'actinide',        block: 'f', period: 7, group: null, gridRow: 10, gridCol: 7,  electronConfig: '[Rn] 5f⁴ 6d¹ 7s²',       protons: 93,  neutrons: 144,electrons: 93,  meltingPoint: 644,     boilingPoint: 4000,    density: 20.25,     electronegativity: 1.36, ionizationEnergy: 605,  electronAffinity: 45.5,  atomicRadius: 155, specificHeat: null,   state: 'solid' },
  { atomicNumber: 94,  symbol: 'Pu', name: 'Plutonium',    nameVi: 'Plutoni',    atomicMass: 244.000, category: 'actinide',        block: 'f', period: 7, group: null, gridRow: 10, gridCol: 8,  electronConfig: '[Rn] 5f⁶ 7s²',           protons: 94,  neutrons: 150,electrons: 94,  meltingPoint: 640,     boilingPoint: 3228,    density: 19.816,    electronegativity: 1.28, ionizationEnergy: 585,  electronAffinity: null,  atomicRadius: 159, specificHeat: null,   state: 'solid' },
  { atomicNumber: 95,  symbol: 'Am', name: 'Americium',    nameVi: 'Americi',    atomicMass: 243.000, category: 'actinide',        block: 'f', period: 7, group: null, gridRow: 10, gridCol: 9,  electronConfig: '[Rn] 5f⁷ 7s²',           protons: 95,  neutrons: 148,electrons: 95,  meltingPoint: 1176,    boilingPoint: 2607,    density: 13.67,     electronegativity: 1.30, ionizationEnergy: 578,  electronAffinity: 9.93,  atomicRadius: 173, specificHeat: null,   state: 'solid' },
  { atomicNumber: 96,  symbol: 'Cm', name: 'Curium',       nameVi: 'Curi',       atomicMass: 247.000, category: 'actinide',        block: 'f', period: 7, group: null, gridRow: 10, gridCol: 10, electronConfig: '[Rn] 5f⁷ 6d¹ 7s²',       protons: 96,  neutrons: 151,electrons: 96,  meltingPoint: 1345,    boilingPoint: 3110,    density: 13.51,     electronegativity: 1.30, ionizationEnergy: 581,  electronAffinity: 27.17, atomicRadius: 174, specificHeat: null,   state: 'solid' },
  { atomicNumber: 97,  symbol: 'Bk', name: 'Berkelium',    nameVi: 'Berkeli',    atomicMass: 247.000, category: 'actinide',        block: 'f', period: 7, group: null, gridRow: 10, gridCol: 11, electronConfig: '[Rn] 5f⁹ 7s²',           protons: 97,  neutrons: 150,electrons: 97,  meltingPoint: 986,     boilingPoint: 2627,    density: 14.78,     electronegativity: 1.30, ionizationEnergy: 601,  electronAffinity: null,  atomicRadius: 170, specificHeat: null,   state: 'solid' },
  { atomicNumber: 98,  symbol: 'Cf', name: 'Californium',  nameVi: 'Californi',  atomicMass: 251.000, category: 'actinide',        block: 'f', period: 7, group: null, gridRow: 10, gridCol: 12, electronConfig: '[Rn] 5f¹⁰ 7s²',          protons: 98,  neutrons: 153,electrons: 98,  meltingPoint: 900,     boilingPoint: 1745,    density: 15.10,     electronegativity: 1.30, ionizationEnergy: 608,  electronAffinity: null,  atomicRadius: 169, specificHeat: null,   state: 'solid' },
  { atomicNumber: 99,  symbol: 'Es', name: 'Einsteinium',  nameVi: 'Einsteini',  atomicMass: 252.000, category: 'actinide',        block: 'f', period: 7, group: null, gridRow: 10, gridCol: 13, electronConfig: '[Rn] 5f¹¹ 7s²',          protons: 99,  neutrons: 153,electrons: 99,  meltingPoint: 860,     boilingPoint: 996,     density: 8.84,      electronegativity: 1.30, ionizationEnergy: 619,  electronAffinity: null,  atomicRadius: null,specificHeat: null,   state: 'solid' },
  { atomicNumber: 100, symbol: 'Fm', name: 'Fermium',      nameVi: 'Fermi',      atomicMass: 257.000, category: 'actinide',        block: 'f', period: 7, group: null, gridRow: 10, gridCol: 14, electronConfig: '[Rn] 5f¹² 7s²',          protons: 100, neutrons: 157,electrons: 100, meltingPoint: 1527,    boilingPoint: null,    density: null,      electronegativity: 1.30, ionizationEnergy: 629,  electronAffinity: null,  atomicRadius: null,specificHeat: null,   state: 'solid' },
  { atomicNumber: 101, symbol: 'Md', name: 'Mendelevium',  nameVi: 'Mendelevi',  atomicMass: 258.000, category: 'actinide',        block: 'f', period: 7, group: null, gridRow: 10, gridCol: 15, electronConfig: '[Rn] 5f¹³ 7s²',          protons: 101, neutrons: 157,electrons: 101, meltingPoint: 827,     boilingPoint: null,    density: null,      electronegativity: 1.30, ionizationEnergy: 635,  electronAffinity: null,  atomicRadius: null,specificHeat: null,   state: 'solid' },
  { atomicNumber: 102, symbol: 'No', name: 'Nobelium',     nameVi: 'Nobeli',     atomicMass: 259.000, category: 'actinide',        block: 'f', period: 7, group: null, gridRow: 10, gridCol: 16, electronConfig: '[Rn] 5f¹⁴ 7s²',          protons: 102, neutrons: 157,electrons: 102, meltingPoint: 827,     boilingPoint: null,    density: null,      electronegativity: 1.30, ionizationEnergy: 642,  electronAffinity: null,  atomicRadius: null,specificHeat: null,   state: 'solid' },
  { atomicNumber: 103, symbol: 'Lr', name: 'Lawrencium',   nameVi: 'Lorenci',    atomicMass: 262.000, category: 'actinide',        block: 'f', period: 7, group: null, gridRow: 10, gridCol: 17, electronConfig: '[Rn] 5f¹⁴ 7s² 7p¹',      protons: 103, neutrons: 159,electrons: 103, meltingPoint: 1627,    boilingPoint: null,    density: null,      electronegativity: 1.30, ionizationEnergy: 479,  electronAffinity: null,  atomicRadius: null,specificHeat: null,   state: 'solid' },
  // Period 7 d-block (after actinide gap)
  { atomicNumber: 104, symbol: 'Rf', name: 'Rutherfordium',nameVi: 'Rutherfordi',atomicMass: 267.000, category: 'transition-metal',block: 'd', period: 7, group: 4,  gridRow: 7, gridCol: 4,  electronConfig: '[Rn] 5f¹⁴ 6d² 7s²',      protons: 104, neutrons: 163,electrons: 104, meltingPoint: null,    boilingPoint: null,    density: null,      electronegativity: null, ionizationEnergy: 580,  electronAffinity: null,  atomicRadius: null,specificHeat: null,   state: 'unknown' },
  { atomicNumber: 105, symbol: 'Db', name: 'Dubnium',      nameVi: 'Dubni',      atomicMass: 268.000, category: 'transition-metal',block: 'd', period: 7, group: 5,  gridRow: 7, gridCol: 5,  electronConfig: '[Rn] 5f¹⁴ 6d³ 7s²',      protons: 105, neutrons: 163,electrons: 105, meltingPoint: null,    boilingPoint: null,    density: null,      electronegativity: null, ionizationEnergy: null, electronAffinity: null,  atomicRadius: null,specificHeat: null,   state: 'unknown' },
  { atomicNumber: 106, symbol: 'Sg', name: 'Seaborgium',   nameVi: 'Seaborgi',   atomicMass: 271.000, category: 'transition-metal',block: 'd', period: 7, group: 6,  gridRow: 7, gridCol: 6,  electronConfig: '[Rn] 5f¹⁴ 6d⁴ 7s²',      protons: 106, neutrons: 165,electrons: 106, meltingPoint: null,    boilingPoint: null,    density: null,      electronegativity: null, ionizationEnergy: null, electronAffinity: null,  atomicRadius: null,specificHeat: null,   state: 'unknown' },
  { atomicNumber: 107, symbol: 'Bh', name: 'Bohrium',      nameVi: 'Bohri',      atomicMass: 270.000, category: 'transition-metal',block: 'd', period: 7, group: 7,  gridRow: 7, gridCol: 7,  electronConfig: '[Rn] 5f¹⁴ 6d⁵ 7s²',      protons: 107, neutrons: 163,electrons: 107, meltingPoint: null,    boilingPoint: null,    density: null,      electronegativity: null, ionizationEnergy: null, electronAffinity: null,  atomicRadius: null,specificHeat: null,   state: 'unknown' },
  { atomicNumber: 108, symbol: 'Hs', name: 'Hassium',      nameVi: 'Hassi',      atomicMass: 277.000, category: 'transition-metal',block: 'd', period: 7, group: 8,  gridRow: 7, gridCol: 8,  electronConfig: '[Rn] 5f¹⁴ 6d⁶ 7s²',      protons: 108, neutrons: 169,electrons: 108, meltingPoint: null,    boilingPoint: null,    density: null,      electronegativity: null, ionizationEnergy: null, electronAffinity: null,  atomicRadius: null,specificHeat: null,   state: 'unknown' },
  { atomicNumber: 109, symbol: 'Mt', name: 'Meitnerium',   nameVi: 'Meitneri',   atomicMass: 278.000, category: 'unknown',         block: 'd', period: 7, group: 9,  gridRow: 7, gridCol: 9,  electronConfig: '[Rn] 5f¹⁴ 6d⁷ 7s²',      protons: 109, neutrons: 169,electrons: 109, meltingPoint: null,    boilingPoint: null,    density: null,      electronegativity: null, ionizationEnergy: null, electronAffinity: null,  atomicRadius: null,specificHeat: null,   state: 'unknown' },
  { atomicNumber: 110, symbol: 'Ds', name: 'Darmstadtium', nameVi: 'Darmstati',  atomicMass: 281.000, category: 'unknown',         block: 'd', period: 7, group: 10, gridRow: 7, gridCol: 10, electronConfig: '[Rn] 5f¹⁴ 6d⁸ 7s²',      protons: 110, neutrons: 171,electrons: 110, meltingPoint: null,    boilingPoint: null,    density: null,      electronegativity: null, ionizationEnergy: null, electronAffinity: null,  atomicRadius: null,specificHeat: null,   state: 'unknown' },
  { atomicNumber: 111, symbol: 'Rg', name: 'Roentgenium',  nameVi: 'Roentgeni',  atomicMass: 282.000, category: 'unknown',         block: 'd', period: 7, group: 11, gridRow: 7, gridCol: 11, electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s¹',     protons: 111, neutrons: 171,electrons: 111, meltingPoint: null,    boilingPoint: null,    density: null,      electronegativity: null, ionizationEnergy: null, electronAffinity: null,  atomicRadius: null,specificHeat: null,   state: 'unknown' },
  { atomicNumber: 112, symbol: 'Cn', name: 'Copernicium',  nameVi: 'Copernici',  atomicMass: 285.000, category: 'transition-metal',block: 'd', period: 7, group: 12, gridRow: 7, gridCol: 12, electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s²',     protons: 112, neutrons: 173,electrons: 112, meltingPoint: null,    boilingPoint: null,    density: null,      electronegativity: null, ionizationEnergy: null, electronAffinity: null,  atomicRadius: null,specificHeat: null,   state: 'unknown' },
  { atomicNumber: 113, symbol: 'Nh', name: 'Nihonium',     nameVi: 'Nihoni',     atomicMass: 286.000, category: 'post-transition', block: 'p', period: 7, group: 13, gridRow: 7, gridCol: 13, electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹', protons: 113, neutrons: 173,electrons: 113, meltingPoint: null,    boilingPoint: null,    density: null,      electronegativity: null, ionizationEnergy: null, electronAffinity: null,  atomicRadius: null,specificHeat: null,   state: 'unknown' },
  { atomicNumber: 114, symbol: 'Fl', name: 'Flerovium',    nameVi: 'Flerovi',    atomicMass: 289.000, category: 'post-transition', block: 'p', period: 7, group: 14, gridRow: 7, gridCol: 14, electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²', protons: 114, neutrons: 175,electrons: 114, meltingPoint: null,    boilingPoint: null,    density: null,      electronegativity: null, ionizationEnergy: null, electronAffinity: null,  atomicRadius: null,specificHeat: null,   state: 'unknown' },
  { atomicNumber: 115, symbol: 'Mc', name: 'Moscovium',    nameVi: 'Moscovi',    atomicMass: 290.000, category: 'post-transition', block: 'p', period: 7, group: 15, gridRow: 7, gridCol: 15, electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³', protons: 115, neutrons: 175,electrons: 115, meltingPoint: null,    boilingPoint: null,    density: null,      electronegativity: null, ionizationEnergy: null, electronAffinity: null,  atomicRadius: null,specificHeat: null,   state: 'unknown' },
  { atomicNumber: 116, symbol: 'Lv', name: 'Livermorium',  nameVi: 'Livermori',  atomicMass: 293.000, category: 'post-transition', block: 'p', period: 7, group: 16, gridRow: 7, gridCol: 16, electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴', protons: 116, neutrons: 177,electrons: 116, meltingPoint: null,    boilingPoint: null,    density: null,      electronegativity: null, ionizationEnergy: null, electronAffinity: null,  atomicRadius: null,specificHeat: null,   state: 'unknown' },
  { atomicNumber: 117, symbol: 'Ts', name: 'Tennessine',   nameVi: 'Tennessine', atomicMass: 294.000, category: 'halogen',         block: 'p', period: 7, group: 17, gridRow: 7, gridCol: 17, electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵', protons: 117, neutrons: 177,electrons: 117, meltingPoint: null,    boilingPoint: null,    density: null,      electronegativity: null, ionizationEnergy: null, electronAffinity: null,  atomicRadius: null,specificHeat: null,   state: 'unknown' },
  { atomicNumber: 118, symbol: 'Og', name: 'Oganesson',    nameVi: 'Oganesson',  atomicMass: 294.000, category: 'noble-gas',       block: 'p', period: 7, group: 18, gridRow: 7, gridCol: 18, electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶', protons: 118, neutrons: 176,electrons: 118, meltingPoint: null,    boilingPoint: null,    density: null,      electronegativity: null, ionizationEnergy: null, electronAffinity: null,  atomicRadius: null,specificHeat: null,   state: 'unknown' },
];

const RADIOACTIVE_WITH_NO_STANDARD_ATOMIC_WEIGHT = new Set([
  43, 61, ...Array.from({ length: 35 }, (_, index) => index + 84),
]);

function atomicWeightFor(atomicNumber: number, legacyMass: number): AtomicWeight {
  // CIAAW 2024 publishes an interval for terrestrial hydrogen materials.
  if (atomicNumber === 1) return { kind: 'interval', min: 1.00784, max: 1.00811 };
  if (RADIOACTIVE_WITH_NO_STANDARD_ATOMIC_WEIGHT.has(atomicNumber)) {
    return { kind: 'mass-number', value: legacyMass };
  }
  return { kind: 'value', value: legacyMass };
}

export const ELEMENTS: Element[] = SNAPSHOT_RECORDS.map((record) => {
  const element = Object.fromEntries(
    Object.entries(record).filter(([key]) => !['atomicMass', 'neutrons', 'atomicRadius', 'specificHeat'].includes(key)),
  );
  const isotope = representativeIsotopeFor(record.atomicNumber);
  const pubChem = PUBCHEM_PROPERTIES[record.atomicNumber];
  const representativeIsotope = isotope && isotope.massNumber !== null && isotope.neutronCount !== null
    ? {
        massNumber: isotope.massNumber,
        neutronCount: isotope.neutronCount,
        source: isotope.source,
      }
    : null;
  return {
    ...element,
    atomicWeight: atomicWeightFor(record.atomicNumber, record.atomicMass),
    // PubChem's downloadable periodic-table CSV does not publish a van der
    // Waals-radius column. Do not relabel its AtomicRadius value as VdW data.
    vanDerWaalsRadius: null,
    representativeIsotope,
    ...pubChem,
  } as Element;
});

export { PERIODIC_TABLE_SNAPSHOT_METADATA };

export const ELEMENTS_BY_NUMBER = new Map<number, Element>(
  ELEMENTS.map(e => [e.atomicNumber, e])
);

export function computeRange(elements: Element[], prop: keyof Element): { min: number; max: number } {
  const values = elements
    .map(e => e[prop] as number | null)
    .filter((v): v is number => v !== null);
  if (values.length === 0) return { min: 0, max: 1 };
  return { min: Math.min(...values), max: Math.max(...values) };
}

export function applyFilters(
  elements: Element[],
  filters: import('./types').FilterState,
  query: string,
  quickRange?: { prop: keyof Element; range: [number, number] } | null
): Set<number> {
  const q = query.trim().toLowerCase();
  const result = new Set<number>();

  for (const el of elements) {
    if (q) {
      const matches =
        el.symbol.toLowerCase().includes(q) ||
        el.nameVi.toLowerCase().includes(q) ||
        el.name.toLowerCase().includes(q) ||
        el.atomicNumber.toString() === q;
      if (!matches) continue;
    }

    const checkRange = (val: number | null, range: [number, number] | null) => {
      if (!range) return true;
      if (val === null) return false;
      return val >= range[0] && val <= range[1];
    };

    if (!checkRange(el.meltingPoint, filters.meltingPoint)) continue;
    if (!checkRange(el.boilingPoint, filters.boilingPoint)) continue;
    if (!checkRange(el.density, filters.density)) continue;
    if (!checkRange(el.electronegativity, filters.electronegativity)) continue;
    if (!checkRange(el.ionizationEnergy, filters.ionizationEnergy)) continue;
    if (!checkRange(el.electronAffinity, filters.electronAffinity)) continue;

    if (filters.blocks.size > 0 && !filters.blocks.has(el.block)) continue;
    if (filters.states.size > 0 && !filters.states.has(el.state)) continue;
    if (filters.categories.size > 0 && !filters.categories.has(el.category)) continue;

    if (quickRange) {
      const v = el[quickRange.prop] as number | null;
      if (v === null) continue;
      if (v < quickRange.range[0] || v > quickRange.range[1]) continue;
    }

    result.add(el.atomicNumber);
  }
  return result;
}
