"use client";

import { memo, useEffect, useRef } from "react";
import { createExposureMap, previewMap, resetExposureMap } from "../../engines/radiography/exposure-map";
import { becquerelMetrics, createBecquerelState, stepBecquerel } from "../../engines/radiography/physics";
import type { BecquerelMetrics, BecquerelParams, BecquerelPhase, BecquerelState } from "../../engines/radiography/types";

type SceneData = { metrics: BecquerelMetrics; preview: number[] };
type Props = { params: BecquerelParams; running: boolean; speed: number; resetSignal: number; command: { phase: BecquerelPhase; token: number }; showRadiation: boolean; showHeatmap: boolean; zoom: number; onData: (data: SceneData) => void; onPhaseChange: (phase: BecquerelPhase) => void };

const phaseLabels: Record<BecquerelPhase, string> = { introduction: "Giới thiệu", preparingPlate: "Chuẩn bị kính ảnh", wrappingPlate: "Bọc giấy đen", placingMetalObject: "Đặt chữ thập kim loại", placingUranium: "Đặt muối uranium", configuringExposure: "Chọn điều kiện phơi", exposing: "Đang phơi", paused: "Tạm dừng", exposureComplete: "Phơi hoàn tất", developing: "Đang tráng ảnh", result: "Kết quả", comparison: "So sánh", completed: "Hoàn thành" };

export const BecquerelScene = memo(function BecquerelScene({ params, running, speed, resetSignal, command, showRadiation, showHeatmap, zoom, onData, onPhaseChange }: Props) {
  const canvasRef = useRef<HTMLCanvasElement>(null), mapRef = useRef(createExposureMap()), stateRef = useRef<BecquerelState>(createBecquerelState(params));
  const latest = useRef({ params, running, speed, showRadiation, showHeatmap, zoom, onData, onPhaseChange }); latest.current = { params, running, speed, showRadiation, showHeatmap, zoom, onData, onPhaseChange };
  const dragging = useRef(false);
  useEffect(() => { resetExposureMap(mapRef.current); stateRef.current = createBecquerelState(params); onPhaseChange("introduction"); }, [resetSignal, params, onPhaseChange]);
  useEffect(() => { stateRef.current = { ...stateRef.current, phase: command.phase, phaseStartedAt: stateRef.current.time, resumePhase: command.phase === "paused" ? stateRef.current.resumePhase : command.phase as Exclude<BecquerelPhase, "paused"> }; }, [command]);
  useEffect(() => {
    const canvas = canvasRef.current, ctx = canvas?.getContext("2d"); if (!canvas || !ctx) return; let frame = 0, last = performance.now(), report = 0, previousPhase = stateRef.current.phase;
    const drawPlate = (x: number, y: number, w: number, h: number, developed: boolean, heatmap: boolean) => {
      ctx.fillStyle = "#cbd5e1"; ctx.beginPath(); ctx.roundRect(x, y, w, h, 8); ctx.fill(); ctx.fillStyle = developed ? "#eee9df" : "#a7c7d8"; ctx.fillRect(x + 7, y + 7, w - 14, h - 14);
      if (developed || heatmap) { const values = previewMap(mapRef.current, latest.current.params, developed), cellW = (w - 14) / mapRef.current.width, cellH = (h - 14) / mapRef.current.height; for (let my = 0; my < mapRef.current.height; my += 2) for (let mx = 0; mx < mapRef.current.width; mx += 2) { const value = values[my * mapRef.current.width + mx]!; ctx.fillStyle = developed ? `rgba(18,24,32,${value})` : `rgba(249,115,22,${value * .55})`; ctx.fillRect(x + 7 + mx * cellW, y + 7 + my * cellH, cellW * 2 + .5, cellH * 2 + .5); } }
    };
    const render = (now: number) => {
      const rect = canvas.getBoundingClientRect(), dpr = Math.min(devicePixelRatio, 2), dt = Math.min((now - last) / 1000, .04); last = now; if (canvas.width !== Math.round(rect.width * dpr) || canvas.height !== Math.round(rect.height * dpr)) { canvas.width = Math.round(rect.width * dpr); canvas.height = Math.round(rect.height * dpr); } ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
      const current = latest.current; if (current.running || stateRef.current.phase === "developing") stateRef.current = stepBecquerel(stateRef.current, current.params, mapRef.current, dt * current.speed); const state = stateRef.current, phaseAge = state.time - state.phaseStartedAt, metrics = becquerelMetrics(state, current.params, mapRef.current); if (state.phase !== previousPhase) { previousPhase = state.phase; current.onPhaseChange(state.phase); }
      if (now - report > 160) { current.onData({ metrics, preview: previewMap(mapRef.current, current.params, metrics.developed) }); report = now; }
      const w = rect.width, h = rect.height, scale = current.zoom / 100, centerX = w > 620 ? w * .38 : w * .48, tableY = h * .79; ctx.clearRect(0, 0, w, h); const background = ctx.createLinearGradient(0, 0, 0, h); background.addColorStop(0, "#071426"); background.addColorStop(1, "#102a43"); ctx.fillStyle = background; ctx.fillRect(0, 0, w, h);
      ctx.fillStyle = "#475569"; ctx.fillRect(w * .08, tableY, w * .84, 12); ctx.fillStyle = "#334155"; ctx.fillRect(w * .13, tableY + 12, 13, h - tableY); ctx.fillRect(w * .84, tableY + 12, 13, h - tableY);
      const plateW = 250 * scale, plateH = 155 * scale, plateX = centerX - plateW / 2, plateY = tableY - plateH - 20;
      const resultMode = ["developing", "result", "comparison", "completed"].includes(state.phase);
      if (resultMode) {
        if (["comparison", "completed"].includes(state.phase)) { const compareW = Math.min(205, w * .3), compareH = compareW * .62, leftX = w * .08, rightX = w * .58, compareY = h * .37; drawPlate(leftX, compareY, compareW, compareH, false, false); drawPlate(rightX, compareY, compareW, compareH, true, true); ctx.fillStyle = "#f8fafc"; ctx.font = "700 13px Inter, sans-serif"; ctx.fillText("TRƯỚC KHI CHIẾU", leftX, compareY - 18); ctx.fillText("SAU KHI CHIẾU VÀ TRÁNG", rightX, compareY - 18); ctx.fillStyle = "#94a3b8"; ctx.font = "500 11px Inter, sans-serif"; ctx.fillText("Nhũ tương chưa nhận bức xạ", leftX, compareY + compareH + 20); ctx.fillText("Vùng đen và bóng chữ thập hiện rõ", rightX, compareY + compareH + 20); }
        else { ctx.fillStyle = "#94a3b8"; ctx.beginPath(); ctx.roundRect(plateX - 22, plateY - 14, plateW + 44, plateH + 42, 15); ctx.fill(); ctx.fillStyle = "#164e63"; ctx.beginPath(); ctx.roundRect(plateX - 14, plateY - 6, plateW + 28, plateH + 26, 11); ctx.fill(); const wave = matchMedia("(prefers-reduced-motion: reduce)").matches ? 0 : Math.sin(now * .008) * 3; ctx.strokeStyle = "rgba(125,211,252,.55)"; ctx.beginPath(); ctx.moveTo(plateX, plateY + 15 + wave); ctx.quadraticCurveTo(centerX, plateY + 5 - wave, plateX + plateW, plateY + 15 + wave); ctx.stroke(); drawPlate(plateX, plateY, plateW, plateH, state.phase !== "developing" || state.developProgress > .25, true); if (state.phase === "developing") { ctx.fillStyle = `rgba(22,78,99,${1 - state.developProgress})`; ctx.fillRect(plateX, plateY, plateW, plateH); } }
      } else {
        drawPlate(plateX, plateY, plateW, plateH, false, current.showHeatmap && ["exposing", "paused", "exposureComplete"].includes(state.phase));
        if (state.phase !== "preparingPlate" && state.phase !== "introduction" && current.params.wrapped >= .5) { ctx.save(); const wrapProgress = state.phase === "wrappingPlate" ? Math.min(1, phaseAge / .9) : 1; ctx.globalAlpha = (current.showHeatmap ? .68 : 1) * wrapProgress; ctx.fillStyle = "#15191e"; ctx.beginPath(); ctx.roundRect(plateX - 8, plateY - 8, plateW + 16, plateH + 16, 8); ctx.fill(); ctx.strokeStyle = "#374151"; ctx.stroke(); ctx.restore(); if (current.showHeatmap && ["exposing", "paused", "exposureComplete"].includes(state.phase)) { ctx.fillStyle = "#fbbf24"; ctx.font = "600 11px Inter, sans-serif"; ctx.fillText("Ảnh ẩn đang tích lũy — chưa phải ảnh đã tráng", plateX + 10, plateY + 20); } }
        if (!["introduction", "preparingPlate", "wrappingPlate"].includes(state.phase) && current.params.material > .5) { ctx.save(); ctx.globalAlpha = state.phase === "placingMetalObject" ? Math.min(1, phaseAge / .8) : 1; ctx.fillStyle = "#94a3b8"; const cx = centerX, cy = plateY + plateH / 2; ctx.fillRect(cx - 13, cy - 55, 26, 110); ctx.fillRect(cx - 55, cy - 13, 110, 26); ctx.strokeStyle = "#e2e8f0"; ctx.strokeRect(cx - 13, cy - 55, 26, 110); ctx.restore(); }
        if (!["introduction", "preparingPlate", "wrappingPlate", "placingMetalObject"].includes(state.phase) && current.params.activity > 0) { const sourceX = centerX + state.sourceX * plateW, targetSourceY = plateY - current.params.distance * 14 - 34, sourceY = state.phase === "placingUranium" ? targetSourceY - Math.max(0, 1 - phaseAge / .9) * 90 : targetSourceY; ctx.shadowColor = "rgba(250,204,21,.35)"; ctx.shadowBlur = 16; ctx.fillStyle = "#b89b3c"; ctx.beginPath(); ctx.roundRect(sourceX - current.params.sourceSize * .55, sourceY - 15, current.params.sourceSize * 1.1, 30, 8); ctx.fill(); ctx.shadowBlur = 0; ctx.fillStyle = "#fef08a"; ctx.font = "600 12px Inter, sans-serif"; ctx.fillText("Muối uranium", sourceX - 42, sourceY - 24);
          if (current.showRadiation) { ctx.strokeStyle = "rgba(253,224,71,.32)"; ctx.setLineDash([4, 5]); for (let index = -4; index <= 4; index++) { const targetX = centerX + index * plateW * .09; ctx.beginPath(); ctx.moveTo(sourceX + index * 6, sourceY + 14); ctx.lineTo(targetX, plateY); ctx.stroke(); if (["exposing", "paused"].includes(state.phase)) { const pulse = ((now / 650 + index * .11) % 1 + 1) % 1, dotX = sourceX + index * 6 + (targetX - sourceX - index * 6) * pulse, dotY = sourceY + 14 + (plateY - sourceY - 14) * pulse; ctx.fillStyle = "rgba(253,224,71,.82)"; ctx.beginPath(); ctx.arc(dotX, dotY, 2.5, 0, Math.PI * 2); ctx.fill(); } } ctx.setLineDash([]); ctx.fillStyle = "#fde68a"; ctx.font = "500 11px Inter, sans-serif"; ctx.fillText("Minh hoạ đường bức xạ — bức xạ thực không nhìn thấy", plateX, plateY - 8); }
        }
        if (w > 620 && !["introduction", "preparingPlate"].includes(state.phase)) { const panelX = w - 224, panelY = 116, panelW = 204; ctx.fillStyle = "rgba(7,20,38,.9)"; ctx.strokeStyle = "rgba(148,163,184,.3)"; ctx.beginPath(); ctx.roundRect(panelX, panelY, panelW, 196, 11); ctx.fill(); ctx.stroke(); ctx.fillStyle = "#f8fafc"; ctx.font = "700 12px Inter, sans-serif"; ctx.fillText("MẶT CẮT CÁC LỚP", panelX + 13, panelY + 22); const layers = [["Muối uranium", "Nguồn tự phát bức xạ", "#d6b84b"], ["Khoảng cách d", "Làm cường độ giảm", "#334155"], ["Vật chắn", "Suy giảm bức xạ", "#94a3b8"], ["Giấy đen", "Chặn ánh sáng nhìn thấy", "#171717"], ["Nhũ tương", "Lưu ảnh ẩn do bức xạ", "#7dd3fc"], ["Tấm kính", "Nâng đỡ lớp nhũ tương", "#cbd5e1"]]; layers.forEach(([name, purpose, color], index) => { const y = panelY + 38 + index * 25; ctx.fillStyle = color; ctx.fillRect(panelX + 13, y - 9, 28, 9); ctx.fillStyle = "#f8fafc"; ctx.font = "600 10.5px Inter, sans-serif"; ctx.fillText(name, panelX + 49, y - 2); ctx.fillStyle = "#94a3b8"; ctx.font = "500 9.5px Inter, sans-serif"; ctx.fillText(purpose, panelX + 49, y + 10); }); }
      }
      ctx.fillStyle = "rgba(7,20,38,.88)"; ctx.beginPath(); ctx.roundRect(18, 18, 190, 82, 10); ctx.fill(); ctx.fillStyle = "#f8fafc"; ctx.font = "700 12px Inter, sans-serif"; ctx.fillText(phaseLabels[state.phase], 30, 39); ctx.font = "500 11px Inter, sans-serif"; ctx.fillStyle = "#cbd5e1"; ctx.fillText(current.params.lightCondition > .5 ? "Điều kiện: có ánh sáng" : "Điều kiện: bóng tối", 30, 58); ctx.fillText(`t = ${metrics.exposureElapsed.toFixed(1)} s · E = ${metrics.meanExposure.toFixed(2)}`, 30, 76); ctx.fillText(`I = ${metrics.intensityAtPlate.toFixed(3)} · truyền ${(metrics.transmission * 100).toFixed(0)}%`, 30, 92);
      frame = requestAnimationFrame(render);
    }; frame = requestAnimationFrame(render); return () => cancelAnimationFrame(frame);
  }, []);
  const moveSource = (clientX: number) => { if (!dragging.current || !canvasRef.current) return; const box = canvasRef.current.getBoundingClientRect(); stateRef.current.sourceX = Math.max(-.35, Math.min(.35, (clientX - box.left - box.width * .48) / (box.width * .5))); };
  return <canvas ref={canvasRef} className="h-full w-full touch-none" aria-label="Mô phỏng thí nghiệm Becquerel với kính ảnh bọc giấy đen" onPointerDown={(event) => { dragging.current = true; event.currentTarget.setPointerCapture(event.pointerId); moveSource(event.clientX); }} onPointerMove={(event) => moveSource(event.clientX)} onPointerUp={() => { dragging.current = false; stateRef.current.sourceX = Math.round(stateRef.current.sourceX * 5) / 5; }} />;
});

export type { SceneData as BecquerelSceneData };
