"use client";

import { type FormEvent, useCallback, useEffect, useState } from "react";
import { Archive, CheckCircle2, Loader2, RefreshCw, Save } from "lucide-react";
import { useSearchParams } from "next/navigation";
import { useAuth } from "@/lib/auth/AuthContext";
import { CLASS_SUBJECTS, type ClassDetail, type ClassStatus, getClassDetail, subjectLabel, updateClass, updateClassStatus } from "@/lib/classroom";
import { ClassHubFrame } from "./ClassHubFrame";

const grades = [10, 11, 12];
export function ClassSettingsPage() {
  const { authFetch } = useAuth(); const classId = useSearchParams().get("classId") ?? "";
  const [detail, setDetail] = useState<ClassDetail | null>(null); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const load = useCallback(async () => { if (!classId) return; try { setDetail(await getClassDetail(authFetch, classId)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Không thể tải cài đặt lớp."); } }, [authFetch, classId]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!detail || detail.status === "INACTIVE") return; setSaving(true); setError(""); try { const data = new FormData(event.currentTarget); const updated = await updateClass(authFetch, detail.id, { name: String(data.get("name") ?? "").trim(), subject: String(data.get("subject")) as ClassDetail["subject"], grade: Number(data.get("grade")), description: String(data.get("description") ?? "").trim() || null }); setDetail(updated); setMessage("Đã lưu thay đổi lớp."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Không thể lưu lớp."); } finally { setSaving(false); } }
  async function toggle() { if (!detail || saving) return; setSaving(true); try { const next: ClassStatus = detail.status === "ACTIVE" ? "INACTIVE" : "ACTIVE"; setDetail(await updateClassStatus(authFetch, detail.id, next)); setMessage(next === "ACTIVE" ? "Đã kích hoạt lại lớp." : "Lớp đã chuyển sang chế độ chỉ đọc."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Không thể đổi trạng thái lớp."); } finally { setSaving(false); } }
  return <ClassHubFrame classId={classId} active="settings"><div className="mt-6 max-w-[680px]"><h1 className="font-libertine text-[32px] font-normal">Cài đặt lớp</h1><p className="mt-1 text-[13px] text-[#6b6b6b]">Cập nhật thông tin hoặc thay đổi trạng thái lớp.</p>{error && <p className="mt-4 text-[13px] text-[#c0492b]">{error}</p>}{message && <p className="mt-4 flex items-center gap-2 text-[13px] text-[#287447]"><CheckCircle2 className="size-4" />{message}</p>}{!detail ? <div className="mt-6 flex items-center gap-2 text-sm text-[#6b6b6b]"><Loader2 className="size-4 animate-spin" /> Đang tải...</div> : <form onSubmit={submit} className="mt-6 rounded-[14px] border border-[#d8d1c9] bg-white p-5"><label className="block text-[12px] font-medium text-[#6b6b6b]">Tên lớp<input name="name" defaultValue={detail.name} disabled={detail.status === "INACTIVE"} required className="mt-2 h-10 w-full rounded-lg border border-[#d8d1c9] bg-[#faf9f7] px-3 text-[13px] disabled:text-[#8a837b]" /></label><div className="mt-4 grid grid-cols-2 gap-3"><label className="text-[12px] font-medium text-[#6b6b6b]">Môn<select name="subject" defaultValue={detail.subject} disabled={detail.status === "INACTIVE"} className="mt-2 h-10 w-full rounded-lg border border-[#d8d1c9] bg-[#faf9f7] px-3 text-[13px]">{CLASS_SUBJECTS.map((subject) => <option key={subject} value={subject}>{subjectLabel(subject)}</option>)}</select></label><label className="text-[12px] font-medium text-[#6b6b6b]">Khối<select name="grade" defaultValue={detail.grade} disabled={detail.status === "INACTIVE"} className="mt-2 h-10 w-full rounded-lg border border-[#d8d1c9] bg-[#faf9f7] px-3 text-[13px]">{grades.map((grade) => <option key={grade} value={grade}>Khối {grade}</option>)}</select></label></div><label className="mt-4 block text-[12px] font-medium text-[#6b6b6b]">Mô tả<textarea name="description" defaultValue={detail.description ?? ""} disabled={detail.status === "INACTIVE"} rows={5} className="mt-2 w-full rounded-lg border border-[#d8d1c9] bg-[#faf9f7] px-3 py-2 text-[13px] disabled:text-[#8a837b]" /></label><div className="mt-5 flex flex-wrap gap-3"><button disabled={saving || detail.status === "INACTIVE"} className="inline-flex h-10 items-center gap-2 rounded-[10px] bg-[#1f1f1f] px-4 text-[13px] font-medium text-white disabled:opacity-50"><Save className="size-4" /> Lưu thông tin</button><button type="button" onClick={() => void toggle()} disabled={saving} className="inline-flex h-10 items-center gap-2 rounded-[10px] border border-[#d8d1c9] px-4 text-[13px] font-medium"><>{detail.status === "ACTIVE" ? <Archive className="size-4" /> : <RefreshCw className="size-4" />}</> {detail.status === "ACTIVE" ? "Lưu trữ lớp" : "Kích hoạt lại lớp"}</button></div>{detail.status === "INACTIVE" && <p className="mt-4 text-[12px] text-[#8a5a35]">Lớp đang ở chế độ chỉ đọc. Kích hoạt lại để chỉnh sửa.</p>}</form>}</div></ClassHubFrame>;
}
