// Dữ liệu slide mẫu (tạm) để demo khung editor + chuyển slide ở Bước 1.
// Sẽ thay bằng dữ liệu từ store/BE ở các bước sau.

import type { Slide } from "./types";

export const seedSlides: Slide[] = [
  {
    id: "slide-1",
    bg: "#ffffff",
    elements: [
      {
        id: "s1-title",
        type: "text",
        x: 80,
        y: 150,
        w: 800,
        h: 120,
        rotation: 0,
        zIndex: 1,
        opacity: 1,
        locked: false,
        text: "Chuyển động thẳng đều",
        fontSize: 56,
        bold: true,
        italic: false,
        color: "#1f1f1f",
        align: "center",
      },
      {
        id: "s1-sub",
        type: "text",
        x: 80,
        y: 290,
        w: 800,
        h: 60,
        rotation: 0,
        zIndex: 2,
        opacity: 1,
        locked: false,
        text: "Bài 1 — Vật lý 10",
        fontSize: 28,
        bold: false,
        italic: false,
        color: "#6b6b6b",
        align: "center",
      },
    ],
  },
  {
    id: "slide-2",
    bg: "#f5f1ec",
    elements: [
      {
        id: "s2-title",
        type: "text",
        x: 60,
        y: 60,
        w: 600,
        h: 70,
        rotation: 0,
        zIndex: 1,
        opacity: 1,
        locked: false,
        text: "Định nghĩa",
        fontSize: 40,
        bold: true,
        italic: false,
        color: "#1f1f1f",
        align: "left",
      },
      {
        id: "s2-box",
        type: "shape",
        x: 60,
        y: 170,
        w: 840,
        h: 260,
        rotation: 0,
        zIndex: 1,
        opacity: 1,
        locked: false,
        shape: "rect",
        fill: "#ffffff",
        stroke: "#d8d1c9",
        strokeW: 2,
        borderRadius: 16,
      },
      {
        id: "s2-body",
        type: "text",
        x: 100,
        y: 210,
        w: 760,
        h: 180,
        rotation: 0,
        zIndex: 2,
        opacity: 1,
        locked: false,
        text: "Chuyển động thẳng đều là chuyển động có quỹ đạo là đường thẳng và có tốc độ trung bình như nhau trên mọi quãng đường.",
        fontSize: 26,
        bold: false,
        italic: false,
        color: "#1f1f1f",
        align: "left",
      },
    ],
  },
  {
    id: "slide-3",
    bg: "#1f1f1f",
    elements: [
      {
        id: "s3-circle",
        type: "shape",
        x: 360,
        y: 120,
        w: 240,
        h: 240,
        rotation: 0,
        zIndex: 1,
        opacity: 1,
        locked: false,
        shape: "ellipse",
        fill: "#d97757",
        stroke: "#d97757",
        strokeW: 0,
        borderRadius: 0,
      },
      {
        id: "s3-formula",
        type: "text",
        x: 80,
        y: 390,
        w: 800,
        h: 80,
        rotation: 0,
        zIndex: 2,
        opacity: 1,
        locked: false,
        text: "s = v · t",
        fontSize: 48,
        bold: true,
        italic: false,
        color: "#ffffff",
        align: "center",
      },
      {
        id: "s3-arrow",
        type: "arrow",
        x: 200,
        y: 240,
        w: 120,
        h: 0,
        rotation: 0,
        zIndex: 3,
        opacity: 1,
        locked: false,
        stroke: "#d97757",
        strokeW: 3,
        dashStyle: "solid",
        arrowHead: "end",
        x1: 0,
        y1: 0,
        x2: 120,
        y2: 0,
      },
    ],
  },
  {
    id: "slide-4",
    bg: "#eef3f8",
    elements: [
      {
        id: "s4-title",
        type: "text",
        x: 80,
        y: 230,
        w: 800,
        h: 80,
        rotation: 0,
        zIndex: 1,
        opacity: 1,
        locked: false,
        text: "Tổng kết",
        fontSize: 44,
        bold: true,
        italic: false,
        color: "#1f4f7a",
        align: "center",
      },
    ],
  },
];
